name: Sync with upstream

# 触发条件：
# 1. 定时触发（每小时检查一次）
# 2. 手动触发（在GitHub界面点击运行）
on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:     # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 步骤1：拉取当前fork仓库的代码
      - name: Checkout fork repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 拉取所有历史，确保能正常合并

      # 步骤2：配置Git用户信息（用于提交合并记录）
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # 步骤3：添加上游仓库地址（替换为原项目地址）
      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/youhunwl/TVAPP.git
          git fetch upstream  # 拉取上游仓库的所有分支

      # 步骤4：合并上游仓库的主分支到当前分支（默认合并到main，如需其他分支请修改）
      - name: Merge upstream changes
        run: |
          git checkout main  # 切换到你要同步的分支（通常是main或master）
          git merge upstream/main  # 合并上游的main分支（根据实际分支名修改）

      # 步骤5：推送合并结果到你的fork仓库
      - name: Push changes to fork
        run: |
          git push origin main  # 推送到你的fork仓库的main分支
